# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g webpack webpack-cli --save-dev
    npm install
    npx webpack --config webpack.config.js
  displayName: 'npm install, run webpack'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/dist'
    contents: '**'
    targetFolder: $(Build.ArtifactStagingDirectory)/webapp
  displayName: 'Copy webapp files'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/webapp'
    artifactName: webapp
  displayName: 'Publish webapp artifact'